
language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - ./node_modules/.bin/gulp clean build

script:
  - npm run test-single-run
  - npm run protractor
